import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import localFont from "next/font/local";
import "./globals.css";
import CookieConsent from "@/app/components/CookieConsent";
import EnvironmentBanner from "@/app/components/EnvironmentBanner";

const gaId = process.env.NEXT_PUBLIC_GA_ID;
const adsenseId = process.env.NEXT_PUBLIC_ADSENSE_ID;

const playfair = localFont({
  src: "../fonts/PlayfairDisplay-Bold.woff2",
  variable: "--font-playfair",
  weight: "700",
  display: "swap",
});

// NEXT_PUBLIC_SITE_URL must be set in Vercel → Project Settings → Environment Variables.
// Example value: https://resumeai.cv
// It is used here for absolute URLs in OG tags, canonical links, and the sitemap.
// In local dev, the fallback keeps things functional without needing the var set.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://resumeai.cv";

export const metadata: Metadata = {
  // metadataBase makes all relative URLs in openGraph/twitter absolute without
  // needing to repeat the domain everywhere. Next.js prepends it automatically.
  metadataBase: new URL(siteUrl),

  title: {
    // The default is used when a page exports no metadata.title of its own.
    // The template applies to any child page that sets a title — %s is replaced
    // by that page's title. Keeps every page branded consistently.
    default: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    template: "%s | ResumeAI",
  },

  description:
    "Free ATS resume checker. Scan your resume for ATS keywords, " +
    "get an explainable match score, run 15 text-based checks, rewrite bullets with AI, " +
    "and download simple PDFs. 9 tools with no subscription fee today.",

  // Keywords matter less to Google than they used to, but still help Bing and
  // give crawlers vocabulary to understand the page's topic.
  keywords: [
    "free ATS resume checker",
    "ATS keyword scanner",
    "ATS score checker free",
    "resume keyword analyzer",
    "ATS friendly resume builder",
    "free resume builder",
    "AI cover letter generator free",
    "resume gap analysis tool",
    "ATS compliance checker",
    "AI bullet rewriter",
    "how to beat ATS",
    "ATS resume keywords by industry",
  ],

  // Open Graph — controls how the page looks when shared on LinkedIn, Slack,
  // Facebook, Discord, etc. The og:image is auto-generated by opengraph-image.tsx
  // in the same directory, so no static file is needed.
  openGraph: {
    type: "website",
    siteName: "ResumeAI",
    title: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    description:
      "Free ATS resume checker. Scan for keywords, get your match " +
      "score, run 15 text-based checks, rewrite bullets with AI, and export simple PDFs. " +
      "9 tools with no subscription fee today.",
    url: "/",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ResumeAI — Free ATS Resume Checker & Keyword Analyzer",
      },
    ],
  },

  // Twitter Card — controls Twitter/X link previews.
  // summary_large_image shows a full-width image card (most impactful).
  twitter: {
    card: "summary_large_image",
    title: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    description:
      "9 free AI tools to pass ATS filters. Keyword extractor, gap analysis, " +
      "compliance checker, AI cover letter, bullet rewriter, PDF export. Free account.",
    images: ["/opengraph-image"],
  },

  // Tell Google to index and follow all links. googleBot fine-tunes the
  // image preview size — "large" unlocks full-size image previews in search.
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Canonical URL prevents duplicate-content penalties if the same page is
  // ever accessible via multiple paths (www vs non-www, trailing slash, etc.).
  alternates: {
    canonical: "/",
  },

  // Google Search Console ownership verification.
  // Next.js renders this as <meta name="google-site-verification" content="...">
  // in the <head> automatically — keep this tag permanently, Google checks it
  // on every re-crawl to confirm continued ownership.
  verification: {
    google: "tAaXD7CA414Jo9wI_ccQ4e4CaKj-_MalVkUkws6sAFA",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} ${playfair.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <link rel="preconnect" href="https://unified-resume-builder-api.onrender.com" />
        <link rel="dns-prefetch" href="https://unified-resume-builder-api.onrender.com" />
        <link rel="dns-prefetch" href="https://pagdtcttkviglyoeuagy.supabase.co" />
        {adsenseId && (
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${adsenseId}`}
            crossOrigin="anonymous"
          />
        )}
        <script dangerouslySetInnerHTML={{ __html: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('consent','default',{'ad_storage':'denied','ad_user_data':'denied','ad_personalization':'denied','analytics_storage':'denied'});try{if(localStorage.getItem('cookie_consent')==='accepted'){gtag('consent','update',{'ad_storage':'granted','ad_user_data':'granted','ad_personalization':'granted','analytics_storage':'granted'})}}catch(e){}` }} />
        <script dangerouslySetInnerHTML={{ __html: `try{var t=localStorage.getItem("theme");if(t==="dark"||(!t&&window.matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.classList.add("dark")}catch(e){}` }} />
      </head>
      <body className="min-h-full flex flex-col">
        <EnvironmentBanner />
        <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-lg focus:bg-indigo-600 focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white focus:shadow-lg">
          Skip to main content
        </a>
        {children}
        <CookieConsent gaId={gaId} />
      </body>
    </html>
  );
}
