import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const gaId = process.env.NEXT_PUBLIC_GA_ID;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["700"],
});

// NEXT_PUBLIC_SITE_URL must be set in Vercel → Project Settings → Environment Variables.
// Example value: https://resumeai.cv
// It is used here for absolute URLs in OG tags, canonical links, and the sitemap.
// In local dev, the fallback keeps things functional without needing the var set.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://resumeai.cv";

export const metadata: Metadata = {
  // metadataBase makes all relative URLs in openGraph/twitter absolute without
  // needing to repeat the domain everywhere. Next.js prepends it automatically.
  metadataBase: new URL(siteUrl),

  title: {
    // The default is used when a page exports no metadata.title of its own.
    // The template applies to any child page that sets a title — %s is replaced
    // by that page's title. Keeps every page branded consistently.
    default: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    template: "%s | ResumeAI",
  },

  description:
    "Free ATS resume checker. Scan your resume for ATS keywords, " +
    "get an instant match score, run 15 formatting checks, rewrite bullets with AI, " +
    "and download ATS-safe PDFs. 9 tools, 100% free.",

  // Keywords matter less to Google than they used to, but still help Bing and
  // give crawlers vocabulary to understand the page's topic.
  keywords: [
    "free ATS resume checker",
    "ATS keyword scanner",
    "ATS score checker free",
    "resume keyword analyzer",
    "ATS friendly resume builder",
    "free resume builder",
    "AI cover letter generator free",
    "resume gap analysis tool",
    "ATS compliance checker",
    "AI bullet rewriter",
    "how to beat ATS",
    "ATS resume keywords by industry",
  ],

  // Open Graph — controls how the page looks when shared on LinkedIn, Slack,
  // Facebook, Discord, etc. The og:image is auto-generated by opengraph-image.tsx
  // in the same directory, so no static file is needed.
  openGraph: {
    type: "website",
    siteName: "ResumeAI",
    title: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    description:
      "Free ATS resume checker. Scan for keywords, get your match " +
      "score, run 15 formatting checks, rewrite bullets with AI, and export ATS-safe PDFs. " +
      "9 tools. 100% free.",
    url: "/",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ResumeAI — Free ATS Resume Checker & Keyword Analyzer",
      },
    ],
  },

  // Twitter Card — controls Twitter/X link previews.
  // summary_large_image shows a full-width image card (most impactful).
  twitter: {
    card: "summary_large_image",
    title: "Free ATS Resume Checker & Keyword Analyzer | ResumeAI",
    description:
      "9 free AI tools to pass ATS filters. Keyword extractor, gap analysis, " +
      "compliance checker, AI cover letter, bullet rewriter, PDF export. Free account.",
    images: ["/opengraph-image"],
  },

  // Tell Google to index and follow all links. googleBot fine-tunes the
  // image preview size — "large" unlocks full-size image previews in search.
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Canonical URL prevents duplicate-content penalties if the same page is
  // ever accessible via multiple paths (www vs non-www, trailing slash, etc.).
  alternates: {
    canonical: "/",
  },

  // Google Search Console ownership verification.
  // Next.js renders this as <meta name="google-site-verification" content="...">
  // in the <head> automatically — keep this tag permanently, Google checks it
  // on every re-crawl to confirm continued ownership.
  verification: {
    google: "tAaXD7CA414Jo9wI_ccQ4e4CaKj-_MalVkUkws6sAFA",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: `try{var t=localStorage.getItem("theme");if(t==="dark"||(!t&&window.matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.classList.add("dark")}catch(e){}` }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
      {gaId && (
        <>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`}
            strategy="afterInteractive"
          />
          <Script id="ga4-init" strategy="afterInteractive">
            {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${gaId}');`}
          </Script>
        </>
      )}
    </html>
  );
}
