import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// NEXT_PUBLIC_SITE_URL must be set in Vercel → Project Settings → Environment Variables.
// Example value: https://resumeai.vercel.app
// It is used here for absolute URLs in OG tags, canonical links, and the sitemap.
// In local dev, the fallback keeps things functional without needing the var set.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://unified-resume-builder.vercel.app";

export const metadata: Metadata = {
  // metadataBase makes all relative URLs in openGraph/twitter absolute without
  // needing to repeat the domain everywhere. Next.js prepends it automatically.
  metadataBase: new URL(siteUrl),

  title: {
    // The default is used when a page exports no metadata.title of its own.
    // The template applies to any child page that sets a title — %s is replaced
    // by that page's title. Keeps every page branded consistently.
    default: "ResumeAI — Free ATS Resume Builder & Keyword Analyzer",
    template: "%s | ResumeAI",
  },

  description:
    "75% of resumes are rejected by ATS filters before a human reads them. " +
    "ResumeAI extracts ATS keywords, scores your resume, runs 15 format checks, " +
    "rewrites bullets with AI, generates cover letters, and exports ATS-safe PDFs — " +
    "9 tools, 100% free, no sign-up.",

  // Keywords matter less to Google than they used to, but still help Bing and
  // give crawlers vocabulary to understand the page's topic.
  keywords: [
    "ATS resume checker",
    "resume keyword analyzer",
    "ATS friendly resume builder",
    "free resume builder",
    "AI cover letter generator",
    "resume gap analysis",
    "ATS compliance checker",
    "AI bullet rewriter",
    "PDF resume download",
    "job application tracker",
    "resume optimizer",
    "ATS score checker",
  ],

  // Open Graph — controls how the page looks when shared on LinkedIn, Slack,
  // Facebook, Discord, etc. The og:image is auto-generated by opengraph-image.tsx
  // in the same directory, so no static file is needed.
  openGraph: {
    type: "website",
    siteName: "ResumeAI",
    title: "ResumeAI — Free ATS Resume Builder & Keyword Analyzer",
    description:
      "Stop losing jobs to ATS filters. Extract keywords, score your resume, " +
      "rewrite bullets with AI, generate cover letters, and download ATS-safe PDFs. " +
      "9 tools. No sign-up. 100% free.",
    url: "/",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "ResumeAI — Free ATS Resume Optimizer",
      },
    ],
  },

  // Twitter Card — controls Twitter/X link previews.
  // summary_large_image shows a full-width image card (most impactful).
  twitter: {
    card: "summary_large_image",
    title: "ResumeAI — Free ATS Resume Builder",
    description:
      "9 free AI tools to pass ATS filters. Keyword extractor, gap analysis, " +
      "AI bullets, cover letter, PDF export. No sign-up.",
    images: ["/opengraph-image"],
  },

  // Tell Google to index and follow all links. googleBot fine-tunes the
  // image preview size — "large" unlocks full-size image previews in search.
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Canonical URL prevents duplicate-content penalties if the same page is
  // ever accessible via multiple paths (www vs non-www, trailing slash, etc.).
  alternates: {
    canonical: "/",
  },

  // Google Search Console ownership verification.
  // Next.js renders this as <meta name="google-site-verification" content="...">
  // in the <head> automatically — keep this tag permanently, Google checks it
  // on every re-crawl to confirm continued ownership.
  verification: {
    google: "tAaXD7CA414Jo9wI_ccQ4e4CaKj-_MalVkUkws6sAFA",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
